### ISSUE TITLE
Keeping track of game rules & global game state

### ISSUE THREAD

**Issue by raduschirliu** [raduschirliu/cpsc585#60]
# Requirements
- [ ] Keeping track of how many human players and how many AIs exist in the scene
- [ ] Setting the number of human players for the game
- [ ] Keep track of stats (total time elapsed, fastest lap, etc.) 
- [ ] Able to position the cars and start the race once everything is set up and configured
- [ ] Ending the race once someone finishes or once everyone finishes

# Implementation
The logic/state for things like:
- Number of human players and AIs
- Positioning the cars and starting the race
- Ending the race
should likely all go into some service (like a `GameplayService`), since we're likely going to be accessing that from multiple scenes and from different players.
  
For things like individual player stats (health, lap time, etc.), that could either:
- Be stored in some array of players in the `GameplayService`, where each entry has a link to each player entity, its relevant components, and also keeps the stats.
- Or be stored directly in components applied to each player car, and the `GameplayService` keeps track of those components for whatever it may need to do (determining who had most kills, etc.)

**Comment by mihailojankovic** [comment]
I'll have a go at this. Idk how to assign it to myself tho :")
